### ISSUE TITLE
Install Error with node/npm

### ISSUE THREAD

**Issue by Subbwae** [tschettervictor/truenas-iocage-mineos#1]
Running the script causes:

-----
writing new private key to '.tmpkey.pem'
-----
writing RSA key
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.2.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"9.9.0","node":"v16.20.1"}

Command: /bin/sh -c cd /usr/local/games/minecraft && npm install npm -g && npm install jsegaert/node-userid && npm install failed!

**Comment by tschettervictor** [comment]
I believe this issue has been resolved for now. I remove one command that updates the npm version.

**Comment by tschettervictor** [comment]
I believe this issue has been resolved for now. I remove one command that updates the npm version.
