### ISSUE TITLE
Building node16 from ports

### ISSUE THREAD

**Issue by lugia19** [tschettervictor/truenas-iocage-mineos#2]
Node16 is now gone, and both node 18 and 20 throw errors when trying to install the project.

Would be handy if the script could be modified to build it from ports (but you would also need to checkout an earlier commit of the ports tree).

Here's my journey to building it from ports:
-Fetch the source tree following [this guide](https://docs.freebsd.org/en/books/handbook/ports/#ports-using)
-Checkout [this commit](https://cgit.freebsd.org/ports/commit/?id=82162fd9a31221ead11c76e180fdfd07b5654b85)
-Try to build www/node16 with portmaster
-Fail due to a signature mismatch in devel/icu, so I went into its directory, did `make fetch && make makesum` to update the distinfo. This is all because they updated the LICENSE file without changing the version number. I did find a version of the file with the original signature [here](https://sourceforge.net/projects/immortalwrt/files/sources/icu4c-74_2-src.tgz/download), if that's more handy.
-Tried again to build node and npm, this time it worked.
-Continue installing mineOS as in the script, and it works.

**Comment by tschettervictor** [comment]
Simple fix implemented. The script now uses yarn to add the packages before installing the userid portion. And I updated the node and openjdk dependancies.
