### ISSUE TITLE
py39-rdiff-backup and py39-supervisor not found

### ISSUE THREAD

**Issue by gabrielcanali** [tschettervictor/truenas-iocage-mineos#5]
Today, when I was installing MineOS, the script completed successfully. However, when I tried to access the IP of the web interface, I got an ERR_CONNECTION_REFUSED error.
Upon checking the mineos.log, I found the following lines during the dependency installation process:

```
  - py39-rdiff-backup... 
pkg: No packages available to install matching 'py39-rdiff-backup' have been found in the repositories
    - py39-rdiff-backup failed to install, retry #1
pkg: No packages available to install matching 'py39-rdiff-backup' have been found in the repositories
    - py39-rdiff-backup failed to install, retry #2
pkg: No packages available to install matching 'py39-rdiff-backup' have been found in the repositories
    - py39-rdiff-backup failed to install, retry #3

  - py39-supervisor... 
pkg: No packages available to install matching 'py39-supervisor' have been found in the repositories
    - py39-supervisor failed to install, retry #1
pkg: No packages available to install matching 'py39-supervisor' have been found in the repositories
    - py39-supervisor failed to install, retry #2
pkg: No packages available to install matching 'py39-supervisor' have been found in the repositories
    - py39-supervisor failed to install, retry #3
```

The solution I found to make it work was to change the dependencies to:

```
  "python311",
  "py311-rdiff-backup",
  "py311-supervisor",
```

Additionally, the issue I described in that pull request still persists (https://github.com/tschettervictor/truenas-iocage-mineos/pull/4). Looking at https://download.freenas.org/, I noticed that version 13.2 is no longer available... (I'm not sure if this is related). I am using version TrueNAS-13.0-U6.2.

Thanks again for the script, it has been immensely helpful, especially for someone like me who is just starting with TrueNAS and other related tools.

**Comment by tschettervictor** [comment]
Yes 13.2 is end of life. We need to use 13.3 and up. 

The reason I’m waiting for CORE 13.3 is because something new was introduced in 13.3 that prevents some services from starting properly using rc scripts.

I’ll update script to use the new packages.

**Comment by tschettervictor** [comment]
Updated script to use python311.

Once CORE 13.3 comes out, the script should automatically pick up version 13.3 for the jails.
