### ISSUE TITLE
MineOS - Startup Loop - Unable to access WebGUI

### ISSUE THREAD

**Issue by TonyPingu115** [tschettervictor/truenas-iocage-mineos#7]
Hello - I have tried to install MineOS into a TrueNAS Core TrueNAS-13.0-U6.2 - Jail 13.3. After several late nights of trying to figure out whats gone wrong or what I am missing I am a bit stumped! Here are two seperate error feedbacks that I have tried to suss out myself.

root@mineos:/usr/local/games/minecraft # node webgui.js
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/usr/local/games/minecraft/webgui.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [

**OR**

root@mineos:/usr/local/games/minecraft # npm start

> mineos-node@1.1.1 start
> node webui.js

(node:20122) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20122) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/local/games/minecraft/node_modules/node-getopt/package.json' of './lib'. Please eitherfix that or report it to the module author
first mineos configuration identified as /etc/mineos.conf
using base_directory:  /var/games/minecraft
Unhandled Rejection at: Promise {
  <rejected> [Error: EPERM: operation not permitted, chmod '/var/games/minecraft/import'] {
    errno: -1,
    code: 'EPERM',
    syscall: 'chmod',
    path: '/var/games/minecraft/import'
  }
} reason: [Error: EPERM: operation not permitted, chmod '/var/games/minecraft/import'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'chmod',

Any support would be amazing as sadly the bare metal I am running does not support a VM at this time! Happy to provide further details please ask! Sorry new to github! Thank you

**Comment by tschettervictor** [comment]
Sadly CORE is slowly going EOL. Only 13.3 jails are supported by the BSD world, and CORE is already EOL at 13.0

They are releasing CORE 13.3 in September, and the BETA version is out already. I’ve been using it in my production environment for a while now so it seems stable.

I would recommend upgrading to 13.3-BETA2 and running the script again.

**Comment by TonyPingu115** [comment]
Hello - thank you so much for replying so fast! Ah I see that makes sense I'll give the 13.3 beta a try tomorrow and wlll update if useful! Otherwise would you personally recommend moving to Scale for long term?? Thanks!

**Comment by tschettervictor** [comment]
I would but only because I’m forced to. I enjoy BSD a lot. But it seems SCALE is becoming the more popular one right now.

**Comment by TonyPingu115** [comment]
Hello again - sadly after a updating to the beta version of Core, Still getting the Spawn Error for MineOS in shell and the refused to connect on browser for the WebGUI.

Let me know if youd like any logs or info on this.

**Comment by tschettervictor** [comment]
Did you run a fresh install of the script?

Try to remove your files from the dataset you created, then rerun the script.

**Comment by TonyPingu115** [comment]
WooHoo! Thank you so much for getting back to me and supporting with this! I was succesful and able to get a 1.16 Minecraft Server up and running! Though i think my poor NAS machine could do with some RAM love so will look to invest there! 

Thank you so much again!
